name: 'Run Unity Cloud Build'
author: 'Condense <hello@condense.live>'
description: 'Runs relevant build via Unity Cloud Build'
inputs:
  unity_cloud_build_api_key:
    description: 'Unity Cloud Build API key'
    required: true
  unity_cloud_build_org_id:
    description: 'Unity Cloud Build Org ID'
    required: true
  unity_cloud_build_project_id:
    description: 'Unity Cloud Build Project ID'
    required: true
  unity_cloud_build_polling_interval:
    description: 'Interval to poll Unity Cloud Build'
    required: false
    default: '60'
  unity_cloud_build_primary_target:
    description: 'Unity Cloud Build Primary Target ID'
    required: true
  unity_cloud_build_target_platform:
    description: 'Unity Cloud Build Target Platform'
    required: true
  unity_cloud_build_download_binary:
    description: 'Download the build binary to env.ARTIFACT_FILEPATH'
    required: false
  unity_cloud_build_create_share:
    description: 'Create a sharing url in UnityCloudBuild and output to env.SHARE_URL'
    required: false
  unity_cloud_build_use_existing_build_number:
    description: 'Force the process to use an existing build number instead of starting a new build'
    required: false
  unity_cloud_build_github_head_ref:
    description: 'github branch reference to build. This will create new build targets if the branch differs from the default target, to support pull requests and tags'
    required: true
  unity_cloud_build_allow_new_build_targets:
    description: 'Set this to false to disable creation of new build targets.'
    required: false
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    UNITY_CLOUD_BUILD_API_KEY: ${{ inputs.unity_cloud_build_api_key }}
    UNITY_CLOUD_BUILD_ORG_ID: ${{ inputs.unity_cloud_build_org_id }}
    UNITY_CLOUD_BUILD_PROJECT_ID: ${{ inputs.unity_cloud_build_project_id }}
    UNITY_CLOUD_BUILD_POLLING_INTERVAL: ${{ inputs.unity_cloud_build_polling_interval }}
    UNITY_CLOUD_BUILD_PRIMARY_TARGET: ${{ inputs.unity_cloud_build_primary_target }}
    UNITY_CLOUD_BUILD_TARGET_PLATFORM: ${{ inputs.unity_cloud_build_target_platform }}
    UNITY_CLOUD_BUILD_DOWNLOAD_BINARY: ${{ inputs.unity_cloud_build_download_binary }}
    UNITY_CLOUD_BUILD_CREATE_SHARE: ${{ inputs.unity_cloud_build_create_share }}
    UNITY_CLOUD_BUILD_USE_EXISTING_BUILD_NUMBER: ${{ inputs.unity_cloud_build_use_existing_build_number }}
    UNITY_CLOUD_BUILD_GITHUB_HEAD_REF: ${{ inputs.unity_cloud_build_github_head_ref }}
    UNITY_CLOUD_BUILD_ALLOW_NEW_BUILD_TARGETS: ${{ inputs.unity_cloud_build_allow_new_build_targets }}
