# Template/reusable workflow
# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Build With Unity Cloud

env:
  IosBundleId: "xxx" # todo: extract from ipa. altool doesn't seem to need this to be correct
  IosBundleVersion: 0 # doesnt seem to need this to be correct. altool uses data in the ipa
  IosBundleShortVersionString: "yyy" # doesnt seem to need this to be correct. altool uses data in the ipa


on:
  workflow_call:
   inputs:
     UnityCloudOrganisation:
       required: true
       type: string
     UnityCloudProject:
       required: true
       type: string
     UnityCloudBuildTarget:
       required: true
       type: string
     UnityCloudTargetPlatform:
       required: false
       type: string
       #deprecationMessage: "UnityCloudTargetPlatform is no longer needed and has no effect." # gr: cannot deprecate workflow inputs, just action inputs
     DownloadBinaryToArtifact:
       required: false
       type: boolean
     UploadToTestFlight:
       required: false
       type: boolean
     ReportShareUrl:
       required: false
       type: boolean
     UploadToOculusReleaseChannel:
       required: false
       type: boolean
     OculusReleaseChannel:
       required: false
       type: string
     SlackBotChannelId:
       required: false
       type: string
     UnityCloudExistingBuildNumber:
       required: false
       type: string # this should be a number, but to allow the input to be used from a workflow_dispatch input, numbers dont work
   secrets:
     UnityCloudBuildApiKey:
       required: true
     SlackBotAuthToken: # passing this enables slack reporting
       required: false
     AppStoreConnect_Auth_Key:
       required: false
     AppStoreConnect_Auth_P8_Base64:
       required: false
     AppStoreConnect_Auth_Issuer:
       required: false
     OculusAppId:
       required: false
     OculusAppSecret:
       required: false


jobs:
  Build:
    runs-on: ubuntu-22.04
    outputs:
     share_url: ${{ steps.build.outputs.SHARE_URL }}
     artifact_filepath: ${{ steps.build.outputs.ARTIFACT_FILEPATH }}
     artifact_filename: ${{ steps.build.outputs.ARTIFACT_FILENAME }}
      
    steps:
    
    - name: Build with Unity Cloud Build
      uses: condensereality/UnityCloudBuildAction@main
      id: build
      with:
       unity_cloud_build_api_key: ${{ secrets.UnityCloudBuildApiKey }}
       unity_cloud_build_org_id: ${{ inputs.UnityCloudOrganisation }}
       unity_cloud_build_project_id: ${{ inputs.UnityCloudProject }}
       unity_cloud_build_polling_interval: 60
       unity_cloud_build_primary_target: ${{ inputs.UnityCloudBuildTarget }}
       unity_cloud_build_download_binary: ${{ inputs.DownloadBinaryToArtifact || inputs.UploadToTestFlight || inputs.UploadToOculusReleaseChannel }}
       unity_cloud_build_create_share: ${{ inputs.ReportShareUrl }}
       # github.ref is the fully formed ref, eg refs/pull/6/merge or refs/tag/v0.1.2
       # github.head_ref is present in pull requests, and is the SOURCE branch (eg. YourFeatureBranch)
       # github.base_ref is present in pull requests, and is the TARGET branch (eg. main)
       unity_cloud_build_github_branch_ref: ${{ github.ref }}
       unity_cloud_build_github_head_ref: ${{ github.head_ref }}
       unity_cloud_build_github_commit_sha: ${{ github.sha }}
       unity_cloud_build_use_existing_build_number: ${{ inputs.UnityCloudExistingBuildNumber }}
    
    - name: Store binary as artifact
      if: ${{ inputs.DownloadBinaryToArtifact || inputs.UploadToTestFlight || inputs.UploadToOculusReleaseChannel }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.build.outputs.ARTIFACT_FILENAME }}
        path: ${{ steps.build.outputs.ARTIFACT_FILEPATH }}
        if-no-files-found: error     
      
      
      
  UploadToTestFlight:
    if: ${{ inputs.UploadToTestFlight }}
    name: Upload to TestFlight
    runs-on: macos-latest
    needs: Build
    env:
      APPSTORECONNECT_AUTH_KEY: ${{ secrets.AppStoreConnect_Auth_Key }}
      APPSTORECONNECT_AUTH_ISSUER: ${{ secrets.AppStoreConnect_Auth_Issuer }}
      APPSTORECONNECT_AUTH_P8_BASE64: ${{ secrets.AppStoreConnect_Auth_P8_Base64 }}
      ARTIFACT_FILENAME: ${{ needs.Build.outputs.artifact_filename }}
      
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_FILENAME }}
          
      # put the authkey p8 in private_keys/ in the filename altool expects
      - name: Get Auth Key.P8
        # xxx.p8 no such file or directory, means you cannot pipe to a file in a directory that doesnt exist
        run: |
         mkdir -p ./private_keys
         echo "$APPSTORECONNECT_AUTH_P8_BASE64" | base64 -d > ./private_keys/AuthKey_$APPSTORECONNECT_AUTH_KEY.p8

      # for debugging any errors below, print out the bundle version from the IPA/plist
      - name: Print Bundle Version
        continue-on-error: true
        env:
         UNZIPPED_PATH: "$GITHUB_WORKSPACE/UnzippedIpa"
        # command used on mac; requires absolute path! defaults read "$(find $(pwd)/unzipped_ipa/Payload/Showcase.app -name '*.app')/Info.plist" CFBundleShortVersionString
        run: |
         unzip -d $UNZIPPED_PATH ${{ env.ARTIFACT_FILENAME }}
         defaults read "$(find $UNZIPPED_PATH -name '*.app')/Info.plist" CFBundleShortVersionString
      
      - name: Upload .ipa to TestFlight
        run: xcrun altool --upload-app --file ${{ env.ARTIFACT_FILENAME }} --type ios --bundle-id ${{ env.IosBundleId }} --bundle-version ${{ env.IosBundleVersion }} --bundle-short-version-string ${{ env.IosBundleShortVersionString }} --apiKey ${APPSTORECONNECT_AUTH_KEY} --apiIssuer ${APPSTORECONNECT_AUTH_ISSUER}
         
      
  UploadToOculusReleaseChannel:
    if: ${{ inputs.UploadToOculusReleaseChannel }}
    name: Upload to Oculus Release Channel
    runs-on: macos-latest
    needs: Build
    env:
      ARTIFACT_FILENAME: ${{ needs.Build.outputs.artifact_filename }}
      
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_FILENAME }}
      
      # unzip the artifact and find the apk inside, save that filename
      - name: Unzip APK from artifact
        id: UnzipApkFromZip
        # the artifact is in fact an .apk in this case, doesn't need unzipping
        #run: |
        # unzip ${{ env.ARTIFACT_FILENAME }}
        # echo APK_FILENAME="$(ls *.apk)" >> "$GITHUB_OUTPUT"
        run: |
         echo APK_FILENAME="${{ env.ARTIFACT_FILENAME }}" >> "$GITHUB_OUTPUT"

      - name: Install ovr-platform-util
        uses: condensereality/setup-ovr-platform-util@main

      - name: Check ovr-platform-util
        run: |
         ovr-platform-util version

      - name: Upload APK to oculus release channel
        uses: condensereality/upload-meta-quest-build@main
        with:
          appId: ${{ secrets.OculusAppId }}
          appSecret: ${{ secrets.OculusAppSecret }}
          apkPath: ${{ steps.UnzipApkFromZip.outputs.APK_FILENAME }}
          releaseChannel: ${{ inputs.OculusReleaseChannel }}
      
      
  ReportToSlack:
   runs-on: ubuntu-22.04
   # can we force this to run (always()) AND only if channel is present?
   #if: ${{ inputs.SlackBotChannelId != '' }}
   if: always()
   needs: [Build,UploadToTestFlight,UploadToOculusReleaseChannel]
   steps:
    - name: Set SHARE_STRING env
      if: needs.Build.outputs.share_url != ''
      env:
       SHARE_URL: ${{ needs.Build.outputs.share_url }}
       UNITY_CLOUD_BUILD_TARGET: ${{ inputs.UnityCloudBuildTarget }}
      run: |
       echo "SHARE_STRING=:gift: $UNITY_CLOUD_BUILD_TARGET $SHARE_URL" >> "$GITHUB_ENV"

    - name: Set TESTFLIGHTRESULT_STRING env
      if: ${{ inputs.UploadToTestFlight }}
      env:
       TFRESULT_STRING: ${{ needs.UploadToTestFlight.result == 'success' && ':green_heart:' || ':x:' }} ${{ needs.UploadToTestFlight.result }}
      run: |
       echo TESTFLIGHTRESULT_STRING="TestFlight $TFRESULT_STRING " >> "$GITHUB_ENV"

    - name: Set OCULUSRELEASERESULT_STRING env
      if: ${{ inputs.UploadToOculusReleaseChannel }}
      env:
       ORRESULT_STRING: ${{ needs.UploadToOculusReleaseChannel.result == 'success' && ':green_heart:' || ':x:' }} ${{ needs.UploadToOculusReleaseChannel.result }}
      run: |
       echo OCULUSRELEASERESULT_STRING="OculusRelease $ORRESULT_STRING " >> "$GITHUB_ENV"


    - name: Notify Slack
      continue-on-error: true
      uses: slackapi/slack-github-action@v1.23.0
      env:
       SLACK_BOT_TOKEN: ${{ secrets.SlackBotAuthToken }}
       RESULT_STRING: ${{ needs.Build.result == 'success' && ':green_heart:' || ':x:' }} ${{ needs.Build.result }}
       RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
       BRANCH_STRING: Branch `${{ github.ref_name }}`
       COMMIT_STRING: <${{ github.event.pull_request.url || github.event.head_commit.url }}|${{ github.event.pull_request.title || github.event.head_commit.message}}>
       
      with:
       channel-id: ${{ inputs.SlackBotChannelId }}
       slack-message: "`${{github.repository}}/${{github.github.ref_name}}${{github.workflow}}` Build Result: ${{env.RESULT_STRING}} ${{ env.TESTFLIGHTRESULT_STRING }} ${{ env.OCULUSRELEASERESULT_STRING }} \n:pencil2: ${{env.COMMIT_STRING}} ${{ env.BRANCH_STRING }} \n:runner: ${{env.RUN_URL}} \n${{ env.SHARE_STRING }}"
